demtrees\CMSBundle\Entity\Post:
    type: entity
    table: post
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        title:
            type: string
            length: 255
        header_image:
            type: string
            length: 255
            nullable: true
        content:
            type: text
        token:
            type: string
            length: 255
            unique: true
        is_public:
            type: boolean
            nullable: true
        created:
            type: datetime
        updated:
            type: datetime
            nullable: true
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: posts
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedValue ]
        preUpdate: [ setUpdatedValue ]
